[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs-18_x", "npm"]

[phases.install]
cmds = ["cd .railway && npm install --omit=dev --no-audit --no-fund"]

[phases.build] 
cmds = ["echo 'Build completed - backend only'"]

[start]
cmd = "cd .railway && npm start"
