[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs"]
cmds = ["cp -r .railway/* . && cp .railway/.* . 2>/dev/null || true"]

[phases.install]
cmds = ["npm install --omit=dev --no-audit --no-fund"]

[phases.build]
cmds = ["echo 'Backend build completed'"]

[start]
cmd = "npm start"
