[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["npm install --only=production --no-audit --no-fund"]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "npm start"
