[phases.setup]
nixPkgs = ["nodejs_22", "nodePackages.npm"]

[phases.install]
cmds = ["npm ci --only=production"]

[phases.build]
cmds = ["echo 'Backend build completed'"]

[start]
cmd = "npm start"
